### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by akhilkpdasan** [JoshMcguigan/traffic#5]
I am getting this error when trying to login
```
thread 'main' panicked at 'Failed to save password to keyring: SecretServiceError(Dbus(D-Bus error: No such interface 'org.freedesktop.DBus.Properties' on object at path / (org.freedesktop.DBus.Error.UnknownMethod)))', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::result::unwrap_failed
   9: traffic::user::credential
  10: traffic::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  15: main
  16: __libc_start_main
  17: _start
```

**Comment by akhilkpdasan** [comment]
Installing `gnome-keyring` fixed this issue

**Comment by JoshMcguigan** [comment]
Thanks for  posting the follow up @akhilkpdasan . If any other users have this issue, please post here so we can track how wide-spread this is.
