### ISSUE TITLE
Failed Login means the next start will not find a password and crash

### ISSUE THREAD

**Issue by lucidBrot** [JoshMcguigan/traffic#9]
I have two issues in one:  
* A failed login means that it will keep automatically failing until `traffic --logout`. See below, I think it's self-explanatory.
* cygwin is not supported. I have run `cargo install traffic` in the cygwin/mintty terminal. All below excerpts are from cygwin. In the windows cmd, traffic works as intended (but only after I did `traffic --logout` to fix the broken key store)

```
Eric@Sharkoon ~
$ traffic
Enter your Github username:
lucidBrot
Enter your Github password (personal access token if 2FA is enabled):thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "Das Handle ist ungültig." }', src\libcore\result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Eric@Sharkoon ~
$ traffic
thread 'main' panicked at 'Could not find password in keychain: WindowsVaultError', src\libcore\result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Eric@Sharkoon ~
$ traffic -V
traffic 0.1.5

```

Second run with RUST_BACKTRACE=1:

```
$ traffic --logout

Eric@Sharkoon ~
$ traffic
Enter your Github username:
lucidBrot
Enter your Github password (personal access token if 2FA is enabled):thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 6, kind: Other, message: "Das Handle ist ungültig." }', src\libcore\result.rs:999:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: BaseThreadInitThunk
  17: RtlUserThreadStart

```

## Expected Behaviour
Let me enter my password, or if that does not work do not store the problematic username.  

## System
Win 10, 64 bit with Cygwin

**Comment by JoshMcguigan** [comment]
Hi, thanks for the detailed bug report. I don't really use traffic much anymore, but I'd gladly review/merge any PR which corrects these issues.

**Comment by lucidBrot** [comment]
I doubt I'll get to it, but I appreciate the encouragement. It works in one of my two terminals, so that's good enough for now :)

They're also deprecating the API endpoint you're using btw
